using ServiceRequests.Web.Requests;

namespace ServiceRequests.Web.Data;

public interface IServiceRequestStore
{
    /// <summary>
    /// Saves a validated request and returns the id generated by the database.
    /// Returns only after the insert is committed; any failure throws.
    /// </summary>
    Task<Guid> InsertAsync(ServiceRequestInput request, CancellationToken cancellationToken);
}
